info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

security:
  user:
    name: admin
    password: admin

quartz:
  threadCount: 15

---

quartz:
  jobstore:
    clustered: true
    instanceId: AUTO


spring:
  profiles: mysql-jobstore
  datasource:
    url: "jdbc:mysql://mysql/onyx"
    username: onyx
    password: onyx
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 10 * 60000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: "SELECT 1"
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false